import dotenv from "dotenv";

dotenv.config();

const { PORT, DATABASE_URI ,
  IMAGEKIT_PUBLIC_KEY,
  IMAGEKIT_PRIVATE_KEY,
  IMAGEKIT_ENDPOINT,
  GOOGLE_CLIENT_ID,
  GOOGLE_CLIENT_SECRET,
  JWT_SECRET,
  BACKEND_URL,
  FRONTEND_URL,
  YOUTUBE_EMBED_API,
  YOUTUBE_CLIENT_ID,
  YOUTUBE_CLIENT_SECRET,
  DOMAIN_URL,
  REDIS_URI,
  REDIS_CACHE_URI,
  REDIS_PUBSUB_URI,
  REDIS_SOCKET_URI,
  // AI Configuration - Generation
  AI_GENERATION_BASE_URL,
  AI_GENERATION_API_KEY,
  AI_GENERATION_MODEL,
  // AI Configuration - Embedding
  AI_EMBEDDING_BASE_URL,
  AI_EMBEDDING_API_KEY,
  AI_EMBEDDING_MODEL,
  // AI Configuration - Image Generation
  AI_IMAGE_GEN_BASE_URL,
  AI_IMAGE_GEN_API_KEY,
  AI_IMAGE_GEN_MODEL,

  //Ai config audio 
  AI_AUDIO_BASE_URL,
  AI_AUDIO_API_KEY,
  AI_AUDIO_MODEL,

  VAPI_API_KEY,
  VAPI_PHONE_NUMBER_ID
 } = process.env;

export const _config = {
  PORT: PORT || 3000,
  AI_AUDIO_BASE_URL,
  AI_AUDIO_API_KEY,
  AI_AUDIO_MODEL,
  DATABASE_URI,
  REDIS_URI,
  REDIS_CACHE_URI: REDIS_CACHE_URI || REDIS_URI,
  REDIS_PUBSUB_URI: REDIS_PUBSUB_URI || REDIS_URI,
  REDIS_SOCKET_URI: REDIS_SOCKET_URI || REDIS_URI,
  IMAGEKIT_PUBLIC_KEY,
  IMAGEKIT_PRIVATE_KEY,
  IMAGEKIT_ENDPOINT,
  GOOGLE_CLIENT_ID,
  GOOGLE_CLIENT_SECRET,
  YOUTUBE_EMBED_API,
  YOUTUBE_CLIENT_ID,
  YOUTUBE_CLIENT_SECRET,
  JWT_SECRET: JWT_SECRET || 'your-jwt-secret',
  BACKEND_URL: BACKEND_URL || 'http://localhost:3000',
  FRONTEND_URL: FRONTEND_URL || 'http://localhost:5173',
  DOMAIN_URL: DOMAIN_URL || 'http://localhost:5173',
  VAPI_API_KEY,
  VAPI_PHONE_NUMBER_ID,
  
  AI_GENERATION_BASE_URL,
  AI_GENERATION_API_KEY,
  AI_GENERATION_MODEL,
  // AI Configuration - Embedding (fallback defaults)
  AI_EMBEDDING_BASE_URL,
  AI_EMBEDDING_API_KEY,
  AI_EMBEDDING_MODEL,
  // AI Configuration - Image Generation
  AI_IMAGE_GEN_BASE_URL,
  AI_IMAGE_GEN_API_KEY,
  AI_IMAGE_GEN_MODEL,
};
